$location = 'centralus'
$loc = 'cus'
$rg = 'NumberService'
$tags = 'project=NumberService', 'repo=jasont-ran/NumberService'
$insights = 'numberservice-insights'
$cosmos = 'numberservice4'
$cosmosDB = 'CosmosNumberTest'
$container = 'CosmosNumberContainer'
